name: ${project.artifactId}
main: ${package}.SynXBukkit
version: ${project.version}
author: ${developer}

commands:
   ${project.artifactId}:
      description: Manage ${project.artifactId}

permissions:
    ${project.artifactId}.manage:
        description: Manage ${project.artifactId}
        default: op
